#!/bin/bash
read -p "L'utilisateur est-il bien $user ? (ex pour Alain Marin = amarin) [N/o] " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Oo]$ ]]
then
echo "Saisir le bon nom d'utilisateur : "
read user
echo "Vous avez choisi de configurer Syncthing pour $user"
else
echo 
fi
